# Generated by Django 4.1.7 on 2023-04-30 19:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('manufacturer', models.CharField(max_length=100)),
                ('default_img', models.FileField(upload_to='media/default')),
                ('category', models.CharField(choices=[('K', 'Kids'), ('M', 'Men'), ('W', 'Women')], max_length=255)),
                ('slug', models.SlugField(blank=True)),
                ('availability_status', models.CharField(choices=[('A', 'Available'), ('U', 'Unavailable'), ('R', 'Restocked')], max_length=24)),
                ('date_added', models.DateTimeField(default=datetime.datetime(2023, 4, 30, 20, 25, 17, 259908))),
                ('newly_added', models.BooleanField(default=True)),
                ('rating', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Boots',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.IntegerField()),
                ('text', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.boots')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BootsVariants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_available', models.IntegerField()),
                ('color', models.CharField(max_length=23)),
                ('image_1', models.FileField(upload_to='media')),
                ('image_2', models.FileField(blank=True, upload_to='media')),
                ('image_3', models.FileField(blank=True, upload_to='media')),
                ('boot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.boots')),
            ],
            options={
                'verbose_name_plural': 'Boots Variants',
            },
        ),
        migrations.AddField(
            model_name='boots',
            name='size',
            field=models.ManyToManyField(to='Core.size'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=355)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
