# Generated by Django 4.1.7 on 2023-05-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_available', models.IntegerField()),
                ('color', models.CharField(max_length=23)),
                ('image_1', models.FileField(upload_to='media')),
                ('image_2', models.FileField(blank=True, upload_to='media')),
                ('image_3', models.FileField(blank=True, upload_to='media')),
            ],
            options={
                'verbose_name_plural': 'Boots Variants',
            },
        ),
        migrations.AlterField(
            model_name='boots',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='BootsVariants',
        ),
        migrations.AddField(
            model_name='boots',
            name='variants',
            field=models.ManyToManyField(to='Core.variants'),
        ),
    ]
