# Generated by Django 4.1.7 on 2023-05-28 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_variants_alter_boots_date_added_delete_bootsvariants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boots',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='variants',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 5, 28, 18, 0, 19, 612978, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variants',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
