# Generated by Django 4.1.7 on 2023-04-30 19:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(blank=True, max_length=18)),
                ('order_summary', models.JSONField(null=True)),
                ('status', models.CharField(choices=[('PEN', 'Pending'), ('APR', 'Approved'), ('DEL', 'Delivered')], max_length=15)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=210.0, max_digits=7)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 4, 30, 19, 25, 17, 272459, tzinfo=datetime.timezone.utc))),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
