# Generated by Django 3.2 on 2023-12-15 20:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 15, 20, 52, 20, 432289, tzinfo=utc)),
        ),
    ]
