# Generated by Django 4.1.7 on 2023-05-28 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_alter_order_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 28, 17, 59, 18, 70899, tzinfo=datetime.timezone.utc)),
        ),
    ]
