# Generated by Django 4.1.7 on 2023-05-30 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_alter_order_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 30, 16, 11, 21, 898564, tzinfo=datetime.timezone.utc)),
        ),
    ]
