# Generated by Django 4.1.7 on 2023-06-18 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0004_alter_order_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 18, 14, 6, 12, 749892, tzinfo=datetime.timezone.utc)),
        ),
    ]
